### ISSUE TITLE
variables from base controller not populated through to atom

### ISSUE THREAD

**Issue by curtismchale** [edalzell/statamic-feeds#4]
When I have this installed it doesn't seem like the variables are getting picked up properly in the base controller so they can get passed to the feed files.

`Undefined property: Edalzell\Feeds\Http\Controllers\Atom::$site_url`

If I hard code that, then the next variable it encounters gives me the same style of error.

**Comment by edalzell** [comment]
ok, I've fixed that, testing it now.

**Comment by phgi** [comment]
I get the same error. What is the reason for the properties of the BaseController being "private"? Should they be "protected"?
