### ISSUE TITLE
error code 1 returned with failed installation

### ISSUE THREAD

**Issue by spanrucker** [edalzell/statamic-feeds#5]
I'm getting this error message on installation:

`Script @php artisan package:discover --ansi handling the 
post-autoload-dump event returned with error code 1`

Have tried deleting composer.lock and vendor folder and reinstalling composer but no luck.

**Comment by edalzell** [comment]
As a work-around, after it fails, can you try `composer require edalzell/feeds` again?

**Comment by spanrucker** [comment]
Yup I did that and the installation seemed to work! I now have a folder at vendor/edalzell/feeds. I'm afraid I've reached the limit of my ability/knowledge here so I'm not sure how to get the feeds working - no worries though I can just wait until you have time to write documentation. If I can help test anything else out let me know! :)
